version: '2'
services:
    app:
        build: .
        command: sh -c "flask db upgrade && flask run --host 0.0.0.0"
        volumes:
            - './app.db:/app.db'
        ports:
            - "5000:5000"
        
