"""empty message

Revision ID: 58d68d0705dd
Revises: b08ac82fb05a
Create Date: 2020-02-14 17:17:39.224914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d68d0705dd'
down_revision = 'b08ac82fb05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tempo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('probabilidade', sa.Integer(), nullable=False),
    sa.Column('precipitacao', sa.Integer(), nullable=False),
    sa.Column('max_temp', sa.Integer(), nullable=False),
    sa.Column('min_temp', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tempo')
    # ### end Alembic commands ###
